n1 = int(input('Digite o primeiro número: '))
n2 = int(input('Digite o segundo número: '))
s = (n1+n2)
sub = (n1-n2)
m = (n1*n2)
d = (n1/n2)
di = (n1//n2)
r = (n1%n2)
print('A soma vale {}, a subtração {}, a multiplicação {}, a divisão {:.2f}, a divisão inteira {} e o resto da divisão vale {}'.format(s, sub, m, d, di,r))